import { Command } from 'commander';
import { initCommand } from './init';
import { utilsHelpCommand } from './help';
import { utilsListCommand } from './list';
import { getCommand } from './get';
import { statusCommand } from './status';
import { commitCommand } from './commit';
import { pullCommand } from './pull';
import { pushCommand } from './push';
import { checkoutCommand } from './checkout';
import { newBranchCommand } from './new-branch';
import { rmBranchCommand } from './rm-branch';
import { diffCommand } from './diff';
import { mergeCommand } from './merge';
import { packCommand } from './pack';
import { increasePatchVersionCommand } from './increase-patch-version';
import { tagVersionCommand } from './tag-version';
import { tagCommand } from './tag';
import { changesSinceCommand } from './changes-since';
import { changesSinceReleaseCommand } from './changes-since-release';
import { compareTagsWithReleaseCommand } from './compare-tags-with-release';
import { commitsSinceCommand } from './commits-since';
import { createLanguageFileCommand } from './create-language-file';
import { importLanguageFilesCommand } from './import-language-files';
import { addEnglishTextsCommand } from './add-english-texts';
import { copyTranslationCommand } from './copy-translation';
import { packTranslationCommand } from './pack-translation';
import { recursiveMinorBumpCommand } from './recursive-minor-bump';
import { listDepsCommand } from './list-deps';
import { findInconsistenciesCommand } from './find-inconsistencies';
import { checkTranslationsCommand } from './check-translations';
import { buildCommand } from './build';
import { updateTranslationsCommand } from './update-translations';
import { validateCommand } from './validate';
import { bumpCommand } from './bump';

export function utilsCommand(): Command {
  const utils = new Command('utils');
  utils.description('Utility commands for H5P library management');

  utils.addCommand(initCommand());
  utils.addCommand(utilsHelpCommand());
  utils.addCommand(utilsListCommand());
  utils.addCommand(getCommand());
  utils.addCommand(statusCommand());
  utils.addCommand(commitCommand());
  utils.addCommand(pullCommand());
  utils.addCommand(pushCommand());
  utils.addCommand(checkoutCommand());
  utils.addCommand(newBranchCommand());
  utils.addCommand(rmBranchCommand());
  utils.addCommand(diffCommand());
  utils.addCommand(mergeCommand());
  utils.addCommand(packCommand());
  utils.addCommand(increasePatchVersionCommand());
  utils.addCommand(tagVersionCommand());
  utils.addCommand(tagCommand());
  utils.addCommand(changesSinceCommand());
  utils.addCommand(changesSinceReleaseCommand());
  utils.addCommand(compareTagsWithReleaseCommand());
  utils.addCommand(commitsSinceCommand());
  utils.addCommand(createLanguageFileCommand());
  utils.addCommand(importLanguageFilesCommand());
  utils.addCommand(addEnglishTextsCommand());
  utils.addCommand(copyTranslationCommand());
  utils.addCommand(packTranslationCommand());
  utils.addCommand(recursiveMinorBumpCommand());
  utils.addCommand(listDepsCommand());
  utils.addCommand(findInconsistenciesCommand());
  utils.addCommand(checkTranslationsCommand());
  utils.addCommand(buildCommand());
  utils.addCommand(updateTranslationsCommand());
  utils.addCommand(validateCommand());
  utils.addCommand(bumpCommand());

  return utils;
}
